
font_family JetBrainsMono Nerd Font 
#font_family Liga SFMono Nerd Font
disable_ligatures never
font_size 15.0
italic_font auto
bold_italic_font auto
bold_font auto 

# Slightly increase line spacing
adjust_line_height 0

#Thicker cursor
#cursor #d2b48c 
#cofee
#cursor #a67b5b 
##orange
#cursor #ff4500
#cursor #ff7f50 
#cursor #a5d8dd

cursor_shape block
cursor_blink_interval 0.0
shell_integration no-cursor

#Disable the terminal bell
enable_audio_bell no
scrollback_lines 10000
background_opacity 0.90

#background_image /home/eres/Pictures/wallpaperflare.com_wallpaper(1).jpg
#background_image_layout cscaled
#background_tint 0.95
#repaint_delay 10

# Enable cursor trails (a value > 0 sets the number of fading trail segments)
cursor_trail 5

# Controls how fast the trail fades out (higher number = faster decay)
cursor_trail_decay 0.1 0.5

# Determines how far the cursor must jump before the trail animation triggers
cursor_trail_start_threshold 2
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# BEGIN_KITTY_THEME
# Default

#include current-theme.conf
include colors-kitty.conf
# END_KITTY_THEME
#foreground #F5CCB0
foreground #a5d8dd

